{% set version = "1.0.1" %}

package:
  name: dart-adna
  version: {{ version }}

source:
  url: https://github.com/genomewalker/dart/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 791dddb3e76404dc28761a980492d82308f02929ead97dff4dc5eddb92001469

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dart-adna', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make
    - pkg-config
  host:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]
  run:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]

test:
  commands:
    - dart --version
    - dart --help
    - dart predict --help
    - dart hits2emi --help
    - dart damage-annotate --help

about:
  home: https://github.com/genomewalker/dart
  license: MIT
  license_file: LICENSE
  summary: DART - Damage-Aware Read Translation for ancient DNA metagenomics
  doc_url: https://github.com/genomewalker/dart/wiki
  dev_url: https://github.com/genomewalker/dart

extra:
  recipe-maintainers:
    - genomewalker
