{% set version = "0.2" %}
{% set sha256 = "bac1a0ad2493af6843424bc900ee1fc682ef1e708991417a68715b26a5bb620e" %}

package:
  name: metadmg
  version: {{ version }}

source:
  url: https://github.com/metaDMG-dev/metaDMG-cpp/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - bzip2
    - xz
    - htslib
    - gsl
    - eigen
  run:
    - htslib
    - zlib
    - bzip2
    - xz
    - gsl
    - eigen

test:
  commands:
    - metaDMG-cpp 2>&1 | grep 'metaDMG-cpp'

about:
  home: https://github.com/metaDMG-dev/metaDMG-cpp
  license: GPLv3, MIT
  #license_file: LICENSE
  summary: "metaDMG-cpp: fast and efficient method for estimating mutation and damage rates in ancient DNA data"
